version: "3.4"
services:
  postgres:
    command: postgres -c 'max_connections=500'
    ports:
      - '5432:5432'
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PG_TRUST_LOCALNET=true
      - 'TZ=Europe/Moscow'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres && psql -U postgres -lqt | cut -d"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      backend: { aliases: [postgres.backend] }

  telegram:
    depends_on:
      - postgres
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
    ports:
      - 8081:8080
      - 5051:5050
    volumes:
      - telegram-logs:/usr/share/app/logs
    networks:
      backend: { aliases: [telegram.backend] }

networks:
  backend:
    driver: bridge

volumes:
  postgres-db-data:
  telegram-logs:
